language: android

android:
  components:
    - build-tools-21.1.2
    - android-21
    - addon-google_apis-google-21
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-addon-google_apis-google-21
    
before_install:
 - chmod +x gradlew

before_install:
  - echo no | android create avd --force -n test -t "Google Inc.:Google APIs:21" --abi google_apis/armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
