language: android

before_install: 
  - chmod +x gradlew
  
before_script:
  - chmod +x gradlew
  
script: ./gradlew connectedAndroidTest

notifications:
  email: false

android:
  components:
    - build-tools-21.1.2
    - android-21
    - addon-google_apis-google-21
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-addon-google_apis-google-21
